backend:
  name: github
  repo: invmv/astro-theme-typography
  branch: main # Branch to update (optional; defaults to master)
  base_url: https://invmy.us.kg
  auth_endpoint: /api/auth
media_folder: public/img
public_folder: img
collections:
  - name: "blog"
    label: "Posts"
    folder: "src/content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "pubDate", widget: "datetime", format: "YYYY-MM-DD" }
      - { label: "Description", name: "description", widget: "string", hint: "附言" }
      - label: "Categories"
        name: "categories"
        widget: "select"
        options: 
          - 交易记录
          - 数字移民
          - 闲来无事
        multiple: true # 允许多选
      - { label: "body", name: "body", widget: "markdown", modes: ["raw","rich_text"] }